/*
* All Action Constants Will Be Store Here
* */


/* PHOTOS */

export const PHOTOS_GET_REQUEST = 'PHOTOS_GET_REQUEST';
export const PHOTOS_GET_SUCCESS = 'PHOTOS_GET_SUCCESS';
export const PHOTOS_GET_FAIL = 'PHOTOS_GET_FAIL';

export const PHOTOS_UPLOAD_REQUEST = 'PHOTOS_UPLOAD_REQUEST';
export const PHOTOS_UPLOAD_SUCCESS = 'PHOTOS_UPLOAD_SUCCESS';
export const PHOTOS_UPLOAD_FAIL = 'PHOTOS_UPLOAD_FAIL';

export const PHOTOS_DELETE_REQUEST = 'PHOTOS_DELETE_REQUEST';
export const PHOTOS_DELETE_SUCCESS = 'PHOTOS_DELETE_SUCCESS';
export const PHOTOS_DELETE_FAIL = 'PHOTOS_DELETE_FAIL';
